export default [
    {
        path:'/AppMain',
        name:'AppMain',
        component:()=>import('@/views/AppMain.vue'),
        redirect: { name: "Home" },
        children:[
            {
                path:'home',
                name:'Home',
                meta:{
                    title:'首页'
                },
                component:()=>import('@/views/Home.vue')
            },
            {
                path:'customeroriginalpicture',
                name:'CustomerCriginalPicture',
                meta:{
                    title:'客户原图'
                },
                component:()=>import('@/views/viewinplm/CustomerOriginalPicture.vue')
            },
            {
                path:'drawingprocess',
                name:'DrawingProcess',
                meta:{
                    title:'图纸工艺'
                },
                component:()=>import('@/views/viewinplm/DrawingProcess.vue')
            },
            {
                path:'inspectioninstruction',
                name:'InspectionInstruction',
                meta:{
                    title:'检验指导书'
                },
                component:()=>import('@/views/viewinplm/InspectionInstruction.vue')
            },
            {
                path:'labelworkinstruction',
                name:'LabelWorkInstruction',
                meta:{
                    title:'标签作业指导书'
                },
                component:()=>import('@/views/viewinplm/LabelWorkInstruction.vue')
            },
            {
                path:'materialinstruction',
                name:'MaterialInstruction',
                meta:{
                    title:'原材料标准'
                },
                component:()=>import('@/views/viewinplm/MaterialInstruction.vue')
            },
            {
                path:'profiledraw',
                name:'ProfileDraw',
                meta:{
                    title:'型材图'
                },
                component:()=>import('@/views/viewinplm/ProfileDraw.vue')
            },
            {
                path:'ProgramDiagram',
                name:'programdiagram',
                meta:{
                    title:'编程用图'
                },
                component:()=>import('@/views/viewinplm/ProgramDiagram.vue')
            },
            {
                path:'WorkInstruction',
                name:'workinstruction',
                meta:{
                    title:'作业指导书'
                },
                component:()=>import('@/views/viewinplm/WorkInstruction.vue')
            },
            {
                path:'ValidDiagram',
                name:'validdiagram',
                meta:{
                    title:'本批有效图'
                },
                component:()=>import('@/views/viewinplm/ValidDiagram.vue')
            },
            {
                path:'i-sipm',
                name:'sipmweb',
                meta:{
                    title:'思普网络平台'
                },
                component:()=>import('@/views/IFrame.vue')
            },
            /*{
                path:'/Admin',
                name:'admin',
                meta:{
                    title:'管理员管理'
                },
                component:()=>import('../components/admin/AdminManage.vue')
            },
            {
                path:'/User',
                name:'user',
                meta:{
                    title:'用户管理'
                },
                component:()=>import('../components/user/UserManage.vue')
            },*/
        ]
    }
]
